---
# tasks file for user_management
- block:
    - name: Calling user creation tasks
      include_tasks: create_users.yml
  when: user_action == "create"

- block:
   - name: Calling user deletion tasks
     include_tasks: delete_users.yml
  when: user_action == "delete"

- block:
   - name: Calling user update tasks
     include_tasks: update_users.yml
  when: user_action == "update"
