#Below playbook used for installing ngnix webserver
---
- hosts: linux
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
    - name: Install Nginx on CentOS
      yum:
       name: nginx
       update_cache: yes
       state: latest
      when: ansible_distribution == 'CentOS'
    - name: Install Nginx on Ubuntu
      apt:
       name: nginx
       update_cache: yes
       state: latest
      when: ansible_distribution == 'Ubuntu'
    - name: Restart nginx
      service:
       name: nginx
       state: restarted
      notify: Check HTTP Service
   # - name: Template index.html-base.j2 to index.html on target
    #  template:
     #   src: index.html-base.j2
      #  dest: "{{ nginx_root_location }}/index.html"
       # mode: 0644
  handlers:
    - name: Check HTTP Service
      uri:
       url: http://{{ ansible_default_ipv4.address }}
       status_code: 200
...
