---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: instance

provisioner:
 name: ansible
 role_paths:
  - /home/ansible/AnsiPro/ktsreddy007/myansible/roles

verifier:
  name: testinfra
