#Below playbook check the file presence and creates it if not present
---
- name: Check and create file with content
  hosts: centos1
  become_user: ansible
  vars:
    target_file: /tmp/removed.txt

  tasks:

    - name: Check if the file already exists
      stat:
        path: "{{ target_file }}"
      register: file_check

    - name: Fail if file exists
      fail:
        msg: "The file {{ target_file }} already exists. Exiting playbook."
      when: file_check.stat.exists

    - name: Create file with content 'hello user'
      copy:
        dest: "{{ target_file }}"
        content: "hello user tejas\n"
      when: not file_check.stat.exists
...
