#Below code shows usage of various file modules
---
#First Play for creating a file 
- name: This is create file module
  hosts: centos1
  gather_facts: True
  tasks:
   - name: create a file
     file:
       path: /tmp/removeme
       owner: root
       mode: 0640
       state: touch
#Second task for Copy module 
   - name: copy file demo
     copy:
       src: /tmp/removed.txt
       dest: /tmp/
#Third task for Blockinfile module for adding some lines
   - name: blockinfile demo
     blockinfile:
       path: /tmp/removed.txt
       block: |
          Hello Teja i am here
       state: present
#Fourth task for Lineinfile module for adding some lines similar to above
   - name: Insert a line without any comments
     lineinfile:
       path: /tmp/removed.txt
       line: "Hello This is inline I am here"
       create: yes
#Fifith task for fetch module
   - name: fetch a file
     fetch:
       src: /tmp/removed.txt
       dest: /tmp/
#Sixth task for Stat module
   - name: Knowing about file with stat module
     stat:
       path: /tmp/removed.txt
     register: filepresence
   - name: Validating file is present or not
     debug:
       msg: "File exists"
     when: filepresence.stat.exists
...
