---
- hosts: ubuntu-c
  gather_facts: True
  tasks:
   # - name: Debug all facts
    #  debug:
     #   var: ansible_facts
    - name: Test hostvars with an ansible fact and collect ansible_port, dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port }}"
    - name: Test hostvars with an ansible fact and collect ansible_port, dict notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_port'] }}"
...
