---
- hosts: centos1
  remote_user: root
  gather_facts: false
  vars:
    motd: |
       Hi Teja
  tasks:
    - name: verifying the task
      command: whoami
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd }}"
        dest: /etc/motd
...

# Above is playbook shows to use Copy module (content parameter)  with no default gather facts so that we deploy a message on Centos 1
