#Below is playbook shows to use Copy module with default gather facts so that we deploy a message on Centos 1
---
- hosts: centos1
  remote_user: root
  tasks:
   - name: verifying the task
     command: whoami

   - name: Configure a MOTD (message of the day)
     copy:
      src: ../roles/files/centos_motd
      dest: /etc/motd
...
