# The below code depicts the udage of handlers 
---
- hosts: centos1
  remote_user: root
  gather_facts: false
  vars:
    motd: |
       Hi Tejassss
  tasks:
    - name: verifying the task
      command: whoami
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd }}"
        dest: /etc/motd
      notify: motd_handi
  handlers:
   - name: motd_handi
     debug:
      msg: motd msg changed
...
