# Install latest NGINX on CentOS/RHEL and Ubuntu/Debian
# using official nginx.org repository
---
- name: Run pre-install tasks
  import_tasks: preinstall_nginx.yml

- name: Show detected OS version
  debug:
    msg: "Installing NGINX on {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

############################
# CENTOS / RHEL
############################
- name: Install NGINX using default OS repos (CentOS 8/9)
  yum:
    name: nginx
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version is version('8', '>=')
    - ansible_distribution_major_version is version('10','<')
############################
# UBUNTU / DEBIAN
############################
- name: Install latest NGINX (Ubuntu)
  apt:
    name: nginx
    state: latest
  when: ansible_os_family == "Debian"

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Allow HTTP traffic via UFW
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ansible_os_family == "Debian"
#- name: Install NGINX on CentOS
#  when: ansible_os_family == "RedHat"
#  yum:
#    name: nginx
#    state: present
#- name: Update Cache & Install NGINX on Ubuntu
#  when: ansible_os_family == "Debian"
#  apt:
#    name: nginx
#    state: present
#    update_cache: true
#- name: Ensure NGINX is started and enabled on (CentOS & Ubuntu)
#  when: ansible_os_family in ["RedHat", "Debian"]
#  service:
#   name: nginx
#   state: started
#   enabled: true
#- name: Ensure default nginx /html directory exists on Centos & Ubuntu
#  when: ansible_os_family in  ["RedHat","Debian"]
#  file:
#    path: "{{ nginx_root }}"
#    state: directory
#    mode: '0755'
#- name: Deploy custom index.html on Centos & Ubutu
#  when: ansible_os_family in ["RedHat","Debian"]
#  copy:
#    src: index.html
#    dest: "{{ nginx_root }}"
#- name: Ensure default nginx /html directory exists on Redhat
#  when: ansible_os_family == "RedHat"
#  file:
 #   path: "{{ nginx_root }}"
  #  state: directory
   # mode: '0755'
#- name: Deploy custom index.html on Redhat
 # when: ansible_os_family  == "RedHat"
  #copy:
   # src: index.html
    #dest: "{{ nginx_root }}"
...
