# Code  for Installing Ngninx
---
- name: Install NGINX on CentOS
  when: ansible_os_family == "RedHat"
  yum:
    name: nginx
    state: present

- name: Update Cache & Install NGINX on Ubuntu
  when: ansible_os_family == "Debian"
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure NGINX is started and enabled on (CentOS & Ubuntu)
  when: ansible_os_family in ["RedHat", "Debian"]
  service:
   name: nginx
   state: started
   enabled: true

- name: Ensure default nginx /html directory exists on Centos & Ubuntu
  when: ansible_os_family in  ["RedHat","Debian"]
  file:
    path: "{{ nginx_root }}"
    state: directory
    mode: '0755'

- name: Deploy custom index.html on Centos & Ubutu
  when: ansible_os_family in ["RedHat","Debian"]
  copy:
    src: index.html
    dest: "{{ nginx_root }}"

#- name: Ensure default nginx /html directory exists on Redhat
#  when: ansible_os_family == "RedHat"
#  file:
 #   path: "{{ nginx_root }}"
  #  state: directory
   # mode: '0755'
#- name: Deploy custom index.html on Redhat
 # when: ansible_os_family  == "RedHat"
  #copy:
   # src: index.html
    #dest: "{{ nginx_root }}"
...
