#Below code check the post installation tasks once nginx installed
---
- name: Ensure NGINX is started and enabled
  service:
    name: nginx
    state: started
    enabled: true
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Allow NGINX to connect to network (SELinux)
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_selinux.status == "enabled"
    - ansible_selinux.mode == "enforcing"

- name: Ensure NGINX root directory exists
  file:
    path: "{{ nginx_root }}"
    state: directory
    mode: '0755'
  notify: restart nginx
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Deploy custom index.html
  copy:
    src: index.html
    dest: "{{ nginx_root }}"
  notify: restart nginx
  when: ansible_os_family in ["RedHat", "Debian"]
...
