#Below is for prerequiste of nginx installation
---
###############
#Centos/Redhat
###############

- name: Include preinstall tasks for CentOS 7
  include_tasks: preinstall_redhat7.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 7

- name: Include preinstall tasks for CentOS 8/9
  include_tasks: preinstall_redhat8_9.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version is version('8', '>=')
    - ansible_distribution_major_version is version('10', '<')

#######################
#Ubuntu / Debian
#######################

- name: Include preinstall tasks for Ubuntu/Debian
  include_tasks: preinstall_debian.yml
  when: ansible_os_family == "Debian"
...
