#Below code is for Centos 8/9 only
---
- name: Install yum-utils for repo management (CentOS 8/9)
  yum:
    name: yum-utils
    state: present

- name: Create NGINX repo file for CentOS 8/9
  copy:
    dest: /etc/yum.repos.d/nginx.repo
    content: |
      [nginx]
      name=NGINX Repository
      baseurl=https://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version is version('8', '>=')
    - ansible_distribution_major_version is version('10', '<')


#- name: Add official NGINX repo (CentOS 8/9)
#  get_url:
#    url: "https://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/nginx.repo"
#    dest: /etc/yum.repos.d/nginx.repo

#- name: Import NGINX GPG key (CentOS 8/9)
#  rpm_key:
#    state: present
#    key: https://nginx.org/keys/nginx_signing.key
...
