#Below playbook used for Nginx installation and uninstallation 
# Its based on Role-based cotroller with nginx action 
---
- name: Nginx master for Installing & Uninstalling using role
  hosts: linux
  become: true

  vars:
    nginx_action: install
    # Use value uninstall for removing
    # Use value install for installing
    # Use value patch for patching
  collections:
    - ktsreddy007.myansible
  roles:
    - nginx
...
