---
-
  hosts: centos1
  gather_facts: False
  vars_prompt:
    - name: username
      private: False
    - name: password
      private: True
  tasks:
    - name: Test vars_prompt
      debug:
        msg: "{{ username }}"
    - name: Test vars_prompt
      debug:
        msg: "{{ password }}"
...
