---
- hosts: centos1
  remote_user: root
  tasks:
   - name: verifying the task
     command: whoami

   - name: Configure a MOTD (message of the day)
     copy:
      src: ../files/centos_motd
      dest: /etc/motd
...
