#Below playbook is for demonstrating the variables value while running the playbook with cmd - ansible-playbook plabook.yaml -e 'motd="THis is Teja\n"'
---
- hosts: centos1
  remote_user: root
  gather_facts: false
  vars:
    motd: |
       Hi Teja
  tasks:
    - name: verifying the task
      command: whoami
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd }}"
        dest: /etc/motd
...
